export MINIO_ACCESS_KEY=minioadmin
export MINIO_SECRET_KEY=minioadmin
export AWS_ACCESS_KEY_ID=minioadmin
export AWS_SECRET_ACCESS_KEY=minioadmin
export WORLD_NAME=New_York_Track
export ROS_AWS_REGION=us-east-1
export AWS_REGION=us-east-1
export AWS_DEFAULT_REGION=us-east-1
export MODEL_S3_PREFIX=rl-deepracer-sagemaker
export MODEL_S3_BUCKET=bucket
export LOCAL=True
export S3_ENDPOINT_URL=http://172.19.240.49:9000
export MARKOV_PRESET_FILE=deepracer.py
export LOCAL_ENV_VAR_JSON_PATH=$(readlink -f ./env_vars.json)
#export LOCAL_EXTRA_DOCKER_COMPOSE_PATH=$(readlink -f ./docker_compose_extra.json)
